version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-service
    ports:
      - 9999:5000
    container_name: frontend
    volumes:
      - ./frontend-service/app:/frontend-service/app
    networks:
      - auction-network

  authentication:
    build:
      context: ./authentication-service
    ports:
      - 5002:5000
    container_name: authentication
    volumes:
      - ./authentication-service/app:/authentication-service/app
    networks:
      - auction-network

  authentication_db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication_db
    image: postgres:latest
    container_name: authentication_db
    networks:
      - auction-network
    ports:
      - 6002:5432
    volumes:
      - authentication_db_volume:/var/lib/postgresql

  user:
    build:
      context: ./user-service-kenny
    ports:
      - 5003:5000
    container_name: user
    volumes:
      - ./user-service/app:/user-service/app
    networks:
      - auction-network

  user_db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    image: postgres:latest
    container_name: user_db
    networks:
      - auction-network
    ports:
      - 6003:5432
    volumes:
      - user_db_volume:/var/lib/postgresql

networks:
  auction-network:
    external: true

volumes:
  authentication_db_volume:
  user_db_volume: