version: '3.8'


services:
  api:
    build:
      context: .
    ports:
      - 5002:5000
    volumes:
      - ./app:/app
    networks:
      - auction-network

  database:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication_db
    image: postgres:latest
    container_name: authentication_db
    networks:
      - auction-network

    ports:
      - 6002:5432
    volumes:
      - db_volume:/var/lib/postgresql

networks:
  auction-network:
    external: true

volumes:
  db_volume:

