version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - 9999:5000
    volumes:
      - ./app:/app
    networks:
      - auction-network

networks:
  auction-network:
    external: true
    
#networks:
#  auction-network:
#    driver: bridge